let path = require('path');
let fs = require('fs');

module.exports = {
  'init': function(browser) {
    browser
      .url('file://' + path.join(__dirname, 'index.html'))
      .waitForElementVisible('body', 1000)
      .assert.value('input', '{"bb":[],"children":[{"bb":[{"type":"item","tagName":"rect","props":[["x",0],["y",0],["width",360],["height",120],["fill","rgba(0,0,0,1)"]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",130],["y",10],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",30],["y",10],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",-70],["y",10],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",230],["y",10],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",330],["y",10],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",130],["y",-90],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",130],["y",110],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",30],["y",-90],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",-70],["y",-90],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",230],["y",-90],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",330],["y",-90],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",30],["y",110],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",-70],["y",110],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",230],["y",110],["width",100],["height",100]]},{"type":"img","tagName":"image","props":[["xlink:href","../image.png"],["x",330],["y",110],["width",100],["height",100]]}],"children":[],"bbClip":"url(#karas-defs-0-0)","visibility":"visible","type":"dom"}],"visibility":"visible","type":"dom","defs":[{"tagName":"clipPath","children":[{"tagName":"rect","props":[["x",0],["y",0],["width",360],["height",120],["fill","#FFF"]]}],"uuid":"karas-defs-0-0"}],"lv":0}')
      .end();
  }
};
