export default {
  GEOM: {
    x1: true,
    y1: true,
    x2: true,
    y2: true,
    controlA: true,
    controlB: true,
    r: true,
    rx: true,
    ry: true,
    begin: true,
    end: true,
    points: true,
    controls: true,
  },
  STYLE: {
    transform: true,
    color: true,
    fontStyle: true,
    strokeWidth: true,
    fill: true,
    backgroundColor: true,
    backgroundImage: true,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundSize: true,
    stroke: true,
    borderBottomColor: true,
    borderLeftColor: true,
    borderRightColor: true,
    borderTopColor: true,
    visibility: true,
    opacity: true,
  },
};
